image: node:20

stages:
  - test
  - build
  - publish
  - trigger
  - deploy

.distributed:
  interruptible: true
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --legacy-peer-deps --cache .npm --prefer-offline
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
    - if [ "$NX_BASE" == "0000000000000000000000000000000000000000" ]; then NX_BASE=$NX_HEAD; fi

variables:
  GIT_DEPTH: 0
  BUILD_CONF: development

format-check:
  stage: test
  extends: .distributed
  script:
    - npx nx format:check --base=$NX_BASE --head=$NX_HEAD
  tags:
    - pdbe-shell

lint:
  stage: test
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3
  tags:
    - pdbe-shell

test:
  stage: test
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t test --parallel=3 --configuration=ci
  tags:
    - pdbe-shell

build:
  stage: build
  image: node:18
  needs:
    - test
    - format-check
    - lint
  extends: .distributed
  rules:
    - if: '$CI_COMMIT_TAG'
      variables:
        BUILD_CONF: production
    - if: "$CI_COMMIT_BRANCH == 'main'"
      variables:
        BUILD_CONF: staging
    - if: "$CI_COMMIT_BRANCH == 'playground'"
      when: never
    - when: always
  script:
    - npx nx run-many -t build --parallel=3 --exclude=playground
    - node ./bin/index.js "$(npx nx show projects --json --type=app --exclude=playground)"
    - cat dynamic-gitlab-ci.yml
  artifacts:
    paths:
      - dist/
      - dynamic-gitlab-ci.yml
    expire_in: 1 week
  tags:
    - pdbe-docker

storybook_build:
  stage: build
  image: node:18
  extends: .distributed
  script:
    - npx nx build-storybook lib-docs
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - pdbe-docker
  except:
    refs:
      - playground

storybook_publish:
  stage: publish
  needs:
    - storybook_build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE --build-arg APP_BASE_HREF=$STORYBOOK_BASE_HREF --tag $CI_REGISTRY_IMAGE/connect-storybook:$CI_COMMIT_SHORT_SHA --file libs/lib-docs/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/connect-storybook:$CI_COMMIT_SHORT_SHA
  tags:
    - pdbe-shell
  except:
    refs:
      - playground

storybook_publish_deploy:
  stage: deploy
  variables:
    UPSTREAM_REF: main
    IMAGE_PATHS: $CI_REGISTRY_IMAGE/connect-storybook:$CI_COMMIT_SHORT_SHA
    IMAGE_NAMES: connect-storybook
    APP_NAME: connect-storybook
  trigger:
    project: pdbe/backend/k8s-deploy-configs
    branch: main
    strategy: depend
  needs:
    - storybook_publish
  except:
    refs:
      - playground

triggers:
  stage: trigger
  needs:
    - build
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml
        job: build
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  except:
    refs:
      - playground

pages:
  stage: deploy
  needs:
    - build
  script:
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
    expire_in: never
  dependencies:
    - build
  except:
    refs:
      - playground

playground_build_and_publish:
  stage: build
  image: node:18
  extends: .distributed
  script:
    - npx nx build playground
    - npm install netlify-cli --force
    - cp netlify.toml dist/apps/playground/browser/
    - node_modules/.bin/netlify deploy --filter playground --site $NETLIFY_PLAYGROUND_SITE_ID --dir dist/apps/playground/browser --prod
  tags:
    - pdbe-docker
  only:
    refs:
      - playground
