image: node:18

stages:
  - test
  - build
  - publish
  - trigger
  - deploy

.distributed:
  interruptible: true
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}

variables:
  GIT_DEPTH: 0

format-check:
  stage: test
  extends: .distributed
  script:
    - npx nx format:check --base=$NX_BASE --head=$NX_HEAD

lint:
  stage: test
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3

test:
  stage: test
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t test --parallel=3 --configuration=ci

build:
  stage: build
  image: node:18
  needs:
    - test
    - format-check
    - lint
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t build --parallel=3
    - node ./bin/index.js "$(npx nx print-affected --type=app --base=$NX_BASE --head=$NX_HEAD)"
    - cat dynamic-gitlab-ci.yml
  artifacts:
    paths:
      - dist/
      - dynamic-gitlab-ci.yml
    expire_in: 1 week

storybook_build:
  stage: build
  image: node:18
  extends: .distributed
  script:
    - npx nx build-storybook lib-docs
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

storybook_publish:
  stage: publish
  needs:
    - storybook_build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE --build-arg APP_BASE_HREF=$STORYBOOK_BASE_HREF --tag $CI_REGISTRY_IMAGE/pdbconnect-storybook --file libs/lib-docs/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/pdbconnect-storybook
  tags:
    - pdbe-shell

storybook_publish_deploy:
  stage: deploy
  variables:
    UPSTREAM_REF: $CI_COMMIT_REF_NAME
    IMAGE_PATHS: $CI_REGISTRY_IMAGE/pdbconnect-storybook
    IMAGE_NAMES: pdbconnect-storybook
    APP_NAME: pdbconnect-storybook
  trigger:
    project: pdbe/backend/k8s-deploy-configs
    branch: main
    strategy: depend
  needs:
    - storybook_publish

triggers:
  stage: trigger
  needs:
    - build
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml
        job: build
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

pages:
  stage: deploy
  needs:
    - build
  script:
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
    expire_in: never
