import { createActionGroup, emptyProps, props } from '@ngrx/store';
import { ProcessedSummary } from '../data-models/summary.model';
import { AssembliesData, DownloadOptionData, EntryMoleculesData, EntryResidueWiseData, ExperimentData } from './entry-store.model';
import { CathMappings, InterProMappings, PfamMappings, ScopMappings } from '../data-models/domains.model';
import { ProcessedQualityScores } from '../data-models/summary-quality-scores.model';
import { ModifiedResidue } from '../data-models/modified-residues.model';
import { KeyValidationStats, ModelQualityXray } from '../data-models/key-validation-stats.model';
import { XRayRefine } from '../data-models/x-ray-refine.model';
import { CitationDetail } from '../data-models/publication.model';
import { RelatedPublication } from '../data-models/related-publications.model';
import { ComplexDetails } from '../data-models/complex-details.model';
import { CarbohydrateMolecule } from '../data-models/carbohydrate-polymer.model';
import {
  BMRBExperimentRawData,
  EMPIARExperimentRawData,
  IRRMCExperimentRawData,
  PDBExperimentRawData,
  SBGRIDExperimentRawData,
} from '../data-models/experiment-raw-data.model';
import { EntryStatus } from '../data-models/status.model';
import { InteractionFromAPI } from '../data-models/interaction.model';
import { ECMapping, GOMapping, UniProtMapping } from '../data-models/uniprot-mapping.model';
import { Symmetry } from '../data-models/assembly.model';
import { PolymerCoverageMolecule } from '../data-models/polymer-coverage.model';
import { LigandMonomer } from '../data-models/ligand-monomers.model';
import { ResidueWiseOutliersMolecule } from '../data-models/residuewise-outliers.model';
import { APIConservationData, APITrackData, APIVariationData } from '@pdbe-lib/pv-nightingale-components';
import { LLMAnnotation } from '../data-models/llm-model';
import { ResidueListed } from '../data-models/residue-listing.model';
import { ProteinSummaryStats } from '../data-models/protein-summary-stats.model';
import { AssemblyUICard, ProcessedAssembly } from './data-processing/assembly-processing';
import { Filter, PreferredAssemblyData } from './data-processing/models/other-models';
import { MacromoleculeUICard } from './data-processing/macromolecule-processing';
import { LigandOrModUICard, ProcessedLigandOrMod } from './data-processing/ligand-processing';
import { DomainsWithMacromolecules, DomainUICard } from './data-processing/domain-processing';
import { ProcessedDomain, ProcessedMacromolecule } from './data-processing/models/processed-entities.model';
import { LigandSummaryStats } from '../data-models/ligand-summary-stats.model';

export const EntryActions = createActionGroup({
  source: 'Ligands Page',
  events: {
    'Set Current EntryId': props<{ entryId: string }>(),
    'Get Summary Data': emptyProps(),
    'Get Summary Data Success': props<{ summaryData: ProcessedSummary }>(),
    'Get Summary Data Failure': emptyProps(),
    'Get Entry Molecules': emptyProps(),
    'Get Entry Molecules Success': props<{ data: EntryMoleculesData }>(),
    'Get Entry Molecules Failure': emptyProps(),
    'Get Experiment': emptyProps(),
    'Get Experiment Success': props<{ data: ExperimentData }>(),
    'Get Experiment Failure': emptyProps(),
    'Get UniprotMapping': emptyProps(),
    'Get UniprotMapping Success': props<{ uniprotMapping: UniProtMapping }>(),
    'Get UniprotMapping Failure': emptyProps(),
    'Get UniprotSummary': props<{ uniprotId: string }>(),
    'Get UniprotSummary Success': props<{ uniprotId: string; unpSummaryData: ProteinSummaryStats }>(),
    'Get UniprotSummary Failure': emptyProps(),
    'Get LigandSummary': emptyProps(),
    'Get LigandSummary Success': props<{ ligandPagesSummary: LigandSummaryStats[] }>(),
    'Get LigandSummary Failure': emptyProps(),
    'Get IsoformsMapping': emptyProps(),
    'Get IsoformsMapping Success': props<{ isoformsMapping: UniProtMapping }>(),
    'Get IsoformsMapping Failure': emptyProps(),
    'Get GOMapping': emptyProps(),
    'Get GOMapping Success': props<{ goMapping: GOMapping }>(),
    'Get GOMapping Failure': emptyProps(),
    'Get ECMapping': emptyProps(),
    'Get ECMapping Success': props<{ ecMapping: ECMapping }>(),
    'Get ECMapping Failure': emptyProps(),
    'Get InterproMapping': emptyProps(),
    'Get InterproMapping Success': props<{ interproMapping: InterProMappings }>(),
    'Get InterproMapping Failure': emptyProps(),
    'Get PfamMapping': emptyProps(),
    'Get PfamMapping Success': props<{ pfamMapping: PfamMappings }>(),
    'Get PfamMapping Failure': emptyProps(),
    'Get Scop175Mapping': emptyProps(),
    'Get Scop175Mapping Success': props<{ scop175Mapping: ScopMappings }>(),
    'Get Scop175Mapping Failure': emptyProps(),
    'Get CathMapping': emptyProps(),
    'Get CathMapping Success': props<{ cathMapping: CathMappings }>(),
    'Get CathMapping Failure': emptyProps(),
    'Get DownloadOptions': emptyProps(),
    'Get DownloadOptions Success': props<{ data: DownloadOptionData }>(),
    'Get DownloadOptions Failure': emptyProps(),
    'Get Summary Quality Scores': emptyProps(),
    'Get Summary Quality Scores Success': props<{ summaryQualityScores: ProcessedQualityScores }>(),
    'Get Summary Quality Scores Failure': emptyProps(),
    'Get PDB Redo Quality Scores': emptyProps(),
    'Get PDB Redo Quality Scores Success': props<{ pdbRedoQualityScore: ProcessedQualityScores }>(),
    'Get PDB Redo Quality Scores Failure': emptyProps(),
    'Get Modifications': emptyProps(),
    'Get Modifications Success': props<{ modifications: ModifiedResidue[] }>(),
    'Get Modifications Failure': emptyProps(),
    'Get Validation Key Stats': emptyProps(),
    'Get Validation Key Stats Success': props<{ validationKeyStats: KeyValidationStats }>(),
    'Get Validation Key Stats Failure': emptyProps(),
    'Get Model Quality Xray': emptyProps(),
    'Get Model Quality Xray Success': props<{ modelQualityXray: ModelQualityXray }>(),
    'Get Model Quality Xray Failure': emptyProps(),
    'Get Validation Xray Refine': emptyProps(),
    'Get Validation Xray Refine Success': props<{ validationXRayRefine: XRayRefine }>(),
    'Get Validation Xray Refine Failure': emptyProps(),
    'Get Primary Publication': emptyProps(),
    'Get Primary Publication Success': props<{ primaryPublication: CitationDetail }>(),
    'Get Primary Publication Failure': emptyProps(),
    'Get Article Citing PDBEntry': emptyProps(),
    'Get Article Citing PDBEntry Success': props<{ articlesCiting: RelatedPublication }>(),
    'Get Article Citing PDBEntry Failure': emptyProps(),
    'Get Preferred Assembly': emptyProps(),
    'Get Preferred Assembly Success': props<{ complexDetails: ComplexDetails[] }>(),
    'Get Preferred Assembly Failure': emptyProps(),
    'Get LLM Annotations': emptyProps(),
    'Get LLM Annotations Success': props<{ llmAnnotations: LLMAnnotation[] }>(),
    'Get LLM Annotations Failure': emptyProps(),
    'Get Symmetry': emptyProps(),
    'Get Symmetry Success': props<{ symmetry: Symmetry[] }>(),
    'Get Symmetry Failure': emptyProps(),
    'Get Assemblies': emptyProps(),
    'Get Assemblies Success': props<{ data: AssembliesData }>(),
    'Get Assemblies Failure': emptyProps(),
    'Get Carbohydrates': emptyProps(),
    'Get Carbohydrates Success': props<{ carbohydrates: CarbohydrateMolecule[] }>(),
    'Get Carbohydrates Failure': emptyProps(),
    'Get Experiment BMRB Raw Data': emptyProps(),
    'Get Experiment BMRB Raw Data Success': props<{ experimentRawDataBMRB: BMRBExperimentRawData[] }>(),
    'Get Experiment BMRB Raw Data Failure': emptyProps(),
    'Get Experiment SBGrid Raw Data': emptyProps(),
    'Get Experiment SBGrid Raw Data Success': props<{ experimentRawDataSBGrid: SBGRIDExperimentRawData }>(),
    'Get Experiment SBGrid Raw Data Failure': emptyProps(),
    'Get Experiment IRRMC Raw Data': emptyProps(),
    'Get Experiment IRRMC Raw Data Success': props<{ experimentRawDataIRRMC: IRRMCExperimentRawData }>(),
    'Get Experiment IRRMC Raw Data Failure': emptyProps(),
    'Get Experiment EMPIAR Raw Data': emptyProps(),
    'Get Experiment EMPIAR Raw Data Success': props<{ experimentRawDataEMPIAR: EMPIARExperimentRawData[] }>(),
    'Get Experiment EMPIAR Raw Data Failure': emptyProps(),
    'Get Experiment PDB Raw Data': emptyProps(),
    'Get Experiment PDB Raw Data Success': props<{ experimentRawDataPDB: PDBExperimentRawData[] }>(),
    'Get Experiment PDB Raw Data Failure': emptyProps(),
    'Get Entry Status': emptyProps(),
    'Get Entry Status Success': props<{ entryStatus: EntryStatus }>(),
    'Get Entry Status Failure': emptyProps(),
    'Get Interactions': props<{ chainId: string; residueId: string }>(),
    'Get Interactions Success': props<{ chainId: string; residueId: string; interactions: InteractionFromAPI }>(),
    'Get Interactions Failure': emptyProps(),
    'Get Residue Listing': props<{ chainId: string }>(),
    'Get Residue Listing Success': props<{ residueListing: ResidueListed[] }>(),
    'Get Residue Listing Failure': emptyProps(),
    'Get Entry Polymer Coverage': emptyProps(),
    'Get Entry Polymer Coverage Success': props<{ polymerCoverage: PolymerCoverageMolecule[] }>(),
    'Get Entry Polymer Coverage Failure': emptyProps(),
    'Get Entry Ligand Monomers': emptyProps(),
    'Get Entry Ligand Monomers Success': props<{ ligandMonomers: LigandMonomer[] }>(),
    'Get Entry Ligand Monomers Failure': emptyProps(),
    'Get Entry Residue Wise Outliers': emptyProps(),
    'Get Entry Residue Wise Outliers Success': props<{ data: EntryResidueWiseData }>(),
    'Get Entry Residue Wise Outliers Failure': emptyProps(),
    'Get Proc Assemblies Cards': emptyProps(),
    'Get Proc Assemblies Cards Success': props<{ procAssembliesCards: AssemblyUICard[] }>(),
    'Get Proc Assemblies Cards Failure': emptyProps(),
    'Get Proc Assemblies Filters': emptyProps(),
    'Get Proc Assemblies Filters Success': props<{ procAssembliesFilters: Filter[] }>(),
    'Get Proc Assemblies Filters Failure': emptyProps(),
    'Get Processed Assemblies': emptyProps(),
    'Get Processed Assemblies Success': props<{ processedAssemblies: ProcessedAssembly[] }>(),
    'Get Processed Assemblies Failure': emptyProps(),
    'Get Proc Macromolecules Cards': emptyProps(),
    'Get Proc Macromolecules Cards Success': props<{ procMacromoleculesCards: MacromoleculeUICard[] }>(),
    'Get Proc Macromolecules Cards Failure': emptyProps(),
    'Get Proc Macromolecules Filters': emptyProps(),
    'Get Proc Macromolecules Filters Success': props<{ procMacromoleculesFilters: Filter[] }>(),
    'Get Proc Macromolecules Filters Failure': emptyProps(),
    'Get Processed Macromolecules': emptyProps(),
    'Get Processed Macromolecules Success': props<{ processedMacromolecules: ProcessedMacromolecule[] }>(),
    'Get Processed Macromolecules Failure': emptyProps(),
    'Get Proc Ligands Cards': emptyProps(),
    'Get Proc Ligands Cards Success': props<{ procLigandsCards: LigandOrModUICard[] }>(),
    'Get Proc Ligands Cards Failure': emptyProps(),
    'Get Proc Ligands Filters': emptyProps(),
    'Get Proc Ligands Filters Success': props<{ procLigandsFilters: Filter[] }>(),
    'Get Proc Ligands Filters Failure': emptyProps(),
    'Get Processed Ligands': emptyProps(),
    'Get Processed Ligands Success': props<{ processedLigands: ProcessedLigandOrMod[] }>(),
    'Get Processed Ligands Failure': emptyProps(),
    'Get Proc Domains Cards': emptyProps(),
    'Get Proc Domains Cards Success': props<{ procDomainsCards: DomainUICard[] }>(),
    'Get Proc Domains Cards Failure': emptyProps(),
    'Get Proc Domains Filters': emptyProps(),
    'Get Proc Domains Filters Success': props<{ procDomainsFilters: Filter[] }>(),
    'Get Proc Domains Filters Failure': emptyProps(),
    'Get Processed Domains': emptyProps(),
    'Get Processed Domains Success': props<{ processedDomains: ProcessedDomain[] }>(),
    'Get Processed Domains Failure': emptyProps(),
    'Get Processed Macromols For LLM': emptyProps(),
    'Get Processed Macromols For LLM Success': props<{ processedMacromoleculesForLLM: ProcessedMacromolecule[] }>(),
    'Get Processed Macromols For LLM Failure': emptyProps(),
    'Get Proc LLM Cards': emptyProps(),
    'Get Proc LLM Cards Success': props<{ procLLMCards: MacromoleculeUICard[] }>(),
    'Get Proc LLM Cards Failure': emptyProps(),
    'Get Processed Domains With Macromols': emptyProps(),
    'Get Processed Domains With Macromols Success': props<{ processedDomainsWithMacromols: DomainsWithMacromolecules }>(),
    'Get Processed Domains With Macromols Failure': emptyProps(),
    'Get Processed Pref Assembly': emptyProps(),
    'Get Processed Pref Assembly Success': props<{ processedPrefAssembly: PreferredAssemblyData | undefined }>(),
    'Get Processed Pref Assembly Failure': emptyProps(),
    'Get Entry Protvista Uniprot Mapping': props<{ entityId: string }>(),
    'Get Entry Protvista Uniprot Mapping Success': props<{ entityId: string; entityPvUniprot: APITrackData }>(),
    'Get Entry Protvista Uniprot Mapping Failure': emptyProps(),
    'Get Entry Protvista Chains': props<{ entityId: string }>(),
    'Get Entry Protvista Chains Success': props<{ entityId: string; entityPvChains: APITrackData }>(),
    'Get Entry Protvista Chains Failure': emptyProps(),
    'Get Entry Protvista Domains': props<{ entityId: string }>(),
    'Get Entry Protvista Domains Success': props<{ entityId: string; entityPvDomains: APITrackData }>(),
    'Get Entry Protvista Domains Failure': emptyProps(),
    'Get Entry Protvista Rfam': props<{ entityId: string }>(),
    'Get Entry Protvista Rfam Success': props<{ entityId: string; entityPvRfam: APITrackData }>(),
    'Get Entry Protvista Rfam Failure': emptyProps(),
    'Get Entry Protvista Secondary Structure': props<{ entityId: string }>(),
    'Get Entry Protvista Secondary Structure Success': props<{ entityId: string; entityPvSecondaryStructure: APITrackData }>(),
    'Get Entry Protvista Secondary Structure Failure': emptyProps(),
    'Get Entry Protvista Binding Sites': props<{ entityId: string }>(),
    'Get Entry Protvista Binding Sites Success': props<{ entityId: string; entityPvBindingSites: APITrackData }>(),
    'Get Entry Protvista Binding Sites Failure': emptyProps(),
    'Get Entry Protvista Interfaces': props<{ entityId: string }>(),
    'Get Entry Protvista Interfaces Success': props<{ entityId: string; entityPvInterfaces: APITrackData }>(),
    'Get Entry Protvista Interfaces Failure': emptyProps(),
    'Get Entry Protvista Annotations': props<{ entityId: string }>(),
    'Get Entry Protvista Annotations Success': props<{ entityId: string; entityPvAnnotations: APITrackData }>(),
    'Get Entry Protvista Annotations Failure': emptyProps(),
    'Get Entry Protvista Conservation': props<{ entityId: string }>(),
    'Get Entry Protvista Conservation Success': props<{ entityId: string; entityPvConservation: APIConservationData }>(),
    'Get Entry Protvista Conservation Failure': emptyProps(),
    'Get Entry Protvista Variation': props<{ entityId: string }>(),
    'Get Entry Protvista Variation Success': props<{ entityId: string; entityPvVariation: APIVariationData }>(),
    'Get Entry Protvista Variation Failure': emptyProps(),
    'Clear Entity Protvista Data': emptyProps(),
  },
});
