import { createActionGroup, emptyProps, props } from '@ngrx/store';
import { ProcessedSummary } from '../data-models/summary.model';
import { AssembliesData, DownloadOptionData, EntryMoleculesData, ExperimentData, UniProtMappingData } from './entry-store.model';
import { CathMappings, InterProMappings, PfamMappings, ScopMappings } from '../data-models/domains.model';
import { ProcessedQualityScores } from '../data-models/summary-quality-scores.model';
import { ModifiedResidue } from '../data-models/modified-residues.model';
import { KeyValidationStats } from '../data-models/key-validation-stats.model';
import { XRayRefine } from '../data-models/x-ray-refine.model';
import { CitationDetail } from '../data-models/publication.model';
import { RelatedPublication } from '../data-models/related-publications.model';
import { ComplexDetails } from '../data-models/complex-details.model';
import { CarbohydrateMolecule } from '../data-models/carbohydrate-polymer.model';
import {
  BMRBExperimentRawData,
  EMPIARExperimentRawData,
  IRRMCExperimentRawData,
  PDBExperimentRawData,
  SBGRIDExperimentRawData,
} from '../data-models/experiment-raw-data.model';
import { EntryStatus } from '../data-models/status.model';
import { Interaction } from '../data-models/interaction.model';
import { ECMapping, GOMapping, UniProtMapping } from '../data-models/uniprot-mapping.model';
import { Symmetry } from '../data-models/assembly.model';
import { PolymerCoverageMolecule } from '../data-models/polymer-coverage.model';
import { LigandMonomer } from '../data-models/ligand-monomers.model';
import { ResidueWiseOutliersMolecule } from '../data-models/residuewise-outliers.model';

export const EntryActions = createActionGroup({
  source: 'Ligands Page',
  events: {
    'Set Current EntryId': props<{ entryId: string }>(),
    'Get Summary Data': emptyProps(),
    'Get Summary Data Success': props<{ summaryData: ProcessedSummary }>(),
    'Get Summary Data Failure': emptyProps(),
    'Get Entry Molecules': emptyProps(),
    'Get Entry Molecules Success': props<{ data: EntryMoleculesData }>(),
    'Get Entry Molecules Failure': emptyProps(),
    'Get Experiment': emptyProps(),
    'Get Experiment Success': props<{ data: ExperimentData }>(),
    'Get Experiment Failure': emptyProps(),
    'Get UniprotMapping': emptyProps(),
    'Get UniprotMapping Success': props<{ data: UniProtMappingData }>(),
    'Get UniprotMapping Failure': emptyProps(),
    'Get IsoformsMapping': emptyProps(),
    'Get IsoformsMapping Success': props<{ isoformsMapping: UniProtMapping }>(),
    'Get IsoformsMapping Failure': emptyProps(),
    'Get GOMapping': emptyProps(),
    'Get GOMapping Success': props<{ goMapping: GOMapping }>(),
    'Get GOMapping Failure': emptyProps(),
    'Get ECMapping': emptyProps(),
    'Get ECMapping Success': props<{ ecMapping: ECMapping }>(),
    'Get ECMapping Failure': emptyProps(),
    'Get InterproMapping': emptyProps(),
    'Get InterproMapping Success': props<{ interproMapping: InterProMappings }>(),
    'Get InterproMapping Failure': emptyProps(),
    'Get PfamMapping': emptyProps(),
    'Get PfamMapping Success': props<{ pfamMapping: PfamMappings }>(),
    'Get PfamMapping Failure': emptyProps(),
    'Get Scop175Mapping': emptyProps(),
    'Get Scop175Mapping Success': props<{ scop175Mapping: ScopMappings }>(),
    'Get Scop175Mapping Failure': emptyProps(),
    'Get CathMapping': emptyProps(),
    'Get CathMapping Success': props<{ cathMapping: CathMappings }>(),
    'Get CathMapping Failure': emptyProps(),
    'Get DownloadOptions': emptyProps(),
    'Get DownloadOptions Success': props<{ data: DownloadOptionData }>(),
    'Get DownloadOptions Failure': emptyProps(),
    'Get Summary Quality Scores': emptyProps(),
    'Get Summary Quality Scores Success': props<{ summaryQualityScores: ProcessedQualityScores }>(),
    'Get Summary Quality Scores Failure': emptyProps(),
    'Get PDB Redo Quality Scores': emptyProps(),
    'Get PDB Redo Quality Scores Success': props<{ pdbRedoQualityScore: ProcessedQualityScores }>(),
    'Get PDB Redo Quality Scores Failure': emptyProps(),
    'Get Modifications': emptyProps(),
    'Get Modifications Success': props<{ modifications: ModifiedResidue[] }>(),
    'Get Modifications Failure': emptyProps(),
    'Get Validation Key Stats': emptyProps(),
    'Get Validation Key Stats Success': props<{ validationKeyStats: KeyValidationStats }>(),
    'Get Validation Key Stats Failure': emptyProps(),
    'Get Validation Xray Refine': emptyProps(),
    'Get Validation Xray Refine Success': props<{ validationXRayRefine: XRayRefine }>(),
    'Get Validation Xray Refine Failure': emptyProps(),
    'Get Primary Publication': emptyProps(),
    'Get Primary Publication Success': props<{ primaryPublication: CitationDetail }>(),
    'Get Primary Publication Failure': emptyProps(),
    'Get Article Citing PDBEntry': emptyProps(),
    'Get Article Citing PDBEntry Success': props<{ articlesCiting: RelatedPublication }>(),
    'Get Article Citing PDBEntry Failure': emptyProps(),
    'Get Preferred Assembly': emptyProps(),
    'Get Preferred Assembly Success': props<{ complexDetails: ComplexDetails[] }>(),
    'Get Preferred Assembly Failure': emptyProps(),
    'Get Symmetry': emptyProps(),
    'Get Symmetry Success': props<{ symmetry: Symmetry[] }>(),
    'Get Symmetry Failure': emptyProps(),
    'Get Assemblies': emptyProps(),
    'Get Assemblies Success': props<{ data: AssembliesData }>(),
    'Get Assemblies Failure': emptyProps(),
    'Get Carbohydrates': emptyProps(),
    'Get Carbohydrates Success': props<{ carbohydrates: CarbohydrateMolecule[] }>(),
    'Get Carbohydrates Failure': emptyProps(),
    'Get Experiment BMRB Raw Data': emptyProps(),
    'Get Experiment BMRB Raw Data Success': props<{ experimentRawDataBMRB: BMRBExperimentRawData[] }>(),
    'Get Experiment BMRB Raw Data Failure': emptyProps(),
    'Get Experiment SBGrid Raw Data': emptyProps(),
    'Get Experiment SBGrid Raw Data Success': props<{ experimentRawDataSBGrid: SBGRIDExperimentRawData }>(),
    'Get Experiment SBGrid Raw Data Failure': emptyProps(),
    'Get Experiment IRRMC Raw Data': emptyProps(),
    'Get Experiment IRRMC Raw Data Success': props<{ experimentRawDataIRRMC: IRRMCExperimentRawData }>(),
    'Get Experiment IRRMC Raw Data Failure': emptyProps(),
    'Get Experiment EMPIAR Raw Data': emptyProps(),
    'Get Experiment EMPIAR Raw Data Success': props<{ experimentRawDataEMPIAR: EMPIARExperimentRawData[] }>(),
    'Get Experiment EMPIAR Raw Data Failure': emptyProps(),
    'Get Experiment PDB Raw Data': emptyProps(),
    'Get Experiment PDB Raw Data Success': props<{ experimentRawDataPDB: PDBExperimentRawData[] }>(),
    'Get Experiment PDB Raw Data Failure': emptyProps(),
    'Get Entry Status': emptyProps(),
    'Get Entry Status Success': props<{ entryStatus: EntryStatus }>(),
    'Get Entry Status Failure': emptyProps(),
    'Get Interactions': emptyProps(),
    'Get Interactions Success': props<{ interactions: Interaction[] }>(),
    'Get Interactions Failure': emptyProps(),
    'Get Entry Polymer Coverage': emptyProps(),
    'Get Entry Polymer Coverage Success': props<{ polymerCoverage: PolymerCoverageMolecule[] }>(),
    'Get Entry Polymer Coverage Failure': emptyProps(),
    'Get Entry Ligand Monomers': emptyProps(),
    'Get Entry Ligand Monomers Success': props<{ ligandMonomers: LigandMonomer[] }>(),
    'Get Entry Ligand Monomers Failure': emptyProps(),
    'Get Entry Residue Wise Outliers': emptyProps(),
    'Get Entry Residue Wise Outliers Success': props<{ residueWiseOutliers: ResidueWiseOutliersMolecule[] }>(),
    'Get Entry Residue Wise Outliers Failure': emptyProps(),
  },
});
