import { createFeatureSelector, createSelector } from '@ngrx/store';
import { ENTRY_STORE_STATE_KEY } from './entry.reducer';
import { EntryStoreState } from './entry-store.model';

const EntryStoreState = createFeatureSelector<EntryStoreState>(ENTRY_STORE_STATE_KEY);

export const EntrySelectors = {
  state: EntryStoreState,
  entryId: createSelector(EntryStoreState, (state: EntryStoreState) => state.entryId),
  summaryData: createSelector(EntryStoreState, (state: EntryStoreState) => state.summaryData),
  macroMolecules: createSelector(EntryStoreState, (state: EntryStoreState) => state.macroMolecules),
  boundLigands: createSelector(EntryStoreState, (state: EntryStoreState) => state.boundLigands),
  organismScientificNames: createSelector(EntryStoreState, (state: EntryStoreState) => state.organismScientificNames),
  hasRNA: createSelector(EntryStoreState, (state: EntryStoreState) => state.hasRNA),
  experimentalDetails: createSelector(EntryStoreState, (state: EntryStoreState) => state.experimentalDetails),
  resolutionValues: createSelector(EntryStoreState, (state: EntryStoreState) => state.resolutionValues),
  experimentalMethod: createSelector(EntryStoreState, (state: EntryStoreState) => state.experimentalMethod),
  uniprotMapping: createSelector(EntryStoreState, (state: EntryStoreState) => state.uniprotMapping),
  proteinPagesSummaryByUniProtIds: createSelector(EntryStoreState, (state: EntryStoreState) => state.proteinPagesSummaryByUniProtIds),
  interproMapping: createSelector(EntryStoreState, (state: EntryStoreState) => state.interproMapping),
  pfamMapping: createSelector(EntryStoreState, (state: EntryStoreState) => state.pfamMapping),
  downloadOptions: createSelector(EntryStoreState, (state: EntryStoreState) => state.downloadOptions),
  viewOptions: createSelector(EntryStoreState, (state: EntryStoreState) => state.viewOptions),
  summaryQualityScores: createSelector(EntryStoreState, (state: EntryStoreState) => state.summaryQualityScores),
  cathMapping: createSelector(EntryStoreState, (state: EntryStoreState) => state.cathMapping),
  scop175Mapping: createSelector(EntryStoreState, (state: EntryStoreState) => state.scop175Mapping),
  modifications: createSelector(EntryStoreState, (state: EntryStoreState) => state.modifications),
  validationKeyStats: createSelector(EntryStoreState, (state: EntryStoreState) => state.validationKeyStats),
  modelQualityXray: createSelector(EntryStoreState, (state: EntryStoreState) => state.modelQualityXray),
  validationXRayRefine: createSelector(EntryStoreState, (state: EntryStoreState) => state.validationXRayRefine),
  primaryPublication: createSelector(EntryStoreState, (state: EntryStoreState) => state.primaryPublication),
  articlesCiting: createSelector(EntryStoreState, (state: EntryStoreState) => state.articlesCiting),
  complexDetails: createSelector(EntryStoreState, (state: EntryStoreState) => state.complexDetails),
  assemblies: createSelector(EntryStoreState, (state: EntryStoreState) => state.assemblies),
  pisaAssemblies: createSelector(EntryStoreState, (state: EntryStoreState) => state.pisaAssemblies),
  carbohydrates: createSelector(EntryStoreState, (state: EntryStoreState) => state.carbohydrates),
  pdbRedoQualityScores: createSelector(EntryStoreState, (state: EntryStoreState) => state.pdbRedoQualityScores),
  experimentRawDataBMRB: createSelector(EntryStoreState, (state: EntryStoreState) => state.experimentRawDataBMRB),
  experimentRawDataSBGrid: createSelector(EntryStoreState, (state: EntryStoreState) => state.experimentRawDataSBGrid),
  experimentRawDataIRRMC: createSelector(EntryStoreState, (state: EntryStoreState) => state.experimentRawDataIRRMC),
  experimentRawDataEMPIAR: createSelector(EntryStoreState, (state: EntryStoreState) => state.experimentRawDataEMPIAR),
  experimentRawDataPDB: createSelector(EntryStoreState, (state: EntryStoreState) => state.experimentRawDataPDB),
  entryStatus: createSelector(EntryStoreState, (state: EntryStoreState) => state.entryStatus),
  interactions: createSelector(EntryStoreState, (state: EntryStoreState) => state.interactions),
  isoformsMapping: createSelector(EntryStoreState, (state: EntryStoreState) => state.isoformsMapping),
  llmAnnotations: createSelector(EntryStoreState, (state: EntryStoreState) => state.llmAnnotations),
  ecMapping: createSelector(EntryStoreState, (state: EntryStoreState) => state.ecMapping),
  goMapping: createSelector(EntryStoreState, (state: EntryStoreState) => state.goMapping),
  symmetry: createSelector(EntryStoreState, (state: EntryStoreState) => state.symmetry),
  polymerCoverage: createSelector(EntryStoreState, (state: EntryStoreState) => state.polymerCoverage),
  ligandMonomers: createSelector(EntryStoreState, (state: EntryStoreState) => state.ligandMonomers),
  residueWiseOutliers: createSelector(EntryStoreState, (state: EntryStoreState) => state.residueWiseOutliers),
  entityPvUniprot: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvUniprot),
  entityPvChains: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvChains),
  entityPvDomains: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvDomains),
  entityPvRfam: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvRfam),
  entityPvSecondaryStructure: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvSecondaryStructure),
  entityPvBindingSites: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvBindingSites),
  entityPvInterfaces: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvInterfaces),
  entityPvAnnotations: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvAnnotations),
  entityPvConservation: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvConservation),
  entityPvVariation: createSelector(EntryStoreState, (state: EntryStoreState) => state.entityPvVariation),
};
