export const downloadParams: any = {
  'archive-mmCIF': { data_format: 'cif' },
  'archive-PDB': { data_format: 'pdb' },
  'assembly-all': { preferred_only: false },
  'assembly-preferred': { preferred_only: true },
  'fasta-combined': { combined: true },
  'fasta-individual': { combined: false },
  'validation-report-full': { report_type: 'full' },
  'validation-report-summary': { report_type: 'summary' },
  'validation-data': { data_format: 'xml' },
  'compound-mmcif-combined': { combined: true },
  'compound-mmcif-individual': { combined: false },
  'model-conventional': {
    atom_naming_scheme: 'conventional',
    conformer: 'model',
  },
  'model-alternative': {
    atom_naming_scheme: 'alternative',
    conformer: 'model',
  },
  'ideal-conventional': {
    atom_naming_scheme: 'conventional',
    conformer: 'ideal',
  },
  'ideal-alternative': {
    atom_naming_scheme: 'alternative',
    conformer: 'ideal',
  },
  'model-combined': { combined: true, conformer: 'model' },
  'model-individual': { combined: false, conformer: 'model' },
  'ideal-combined': { combined: true, conformer: 'ideal' },
  'ideal-individual': { combined: false, conformer: 'ideal' },
};

export const fdsTypeDict: any = {
  'archive-mmCIF': 'archive',
  'archive-PDB': 'archive',
  'updated-mmCIF': 'updated',
  'assembly-all': 'assemblies',
  'assembly-preferred': 'assemblies',
  'structure-factors': 'structure-factors',
  'nmr-data': 'nmr-data',
  'fasta-combined': 'sequences',
  'fasta-individual': 'sequences',
  'validation-report-full': 'validation-report',
  'validation-report-summary': 'validation-report',
  'validation-data': 'validation-data',
  'map-coefficients': 'map-coefficients',
  'compound-mmcif-combined': 'mmcif',
  'compound-mmcif-individual': 'mmcif',
  'model-conventional': 'pdb',
  'model-alternative': 'pdb',
  'ideal-conventional': 'pdb',
  'ideal-alternative': 'pdb',
  'model-combined': 'sdf',
  'model-individual': 'sdf',
  'ideal-combined': 'sdf',
  'ideal-individual': 'sdf',
  sifts: 'sifts',
};
